spring:
  application:
    name: externo
  output.ansi.enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enabled: true
            required: true


formato-data-validade: "yyyy-MM-dd"